POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
    "date": "2016-01-01",
    "type": "OccupationalHealthcare",
    "specialist": "Thirteen",
    "description": "Patient lost his prescription drugs.",
    "employerName": "CSI Miami"
}